### ISSUE TITLE
GL shader compile failures + 0x502 cascades during 30-min playthrough

### ISSUE THREAD

**Issue by blackden** [blackden/xray-16#22]
## Symptom

CHK_GL clean run (Block 2 of done-criteria) found the log is NOT clean. Counts from this session:

- **1152× \`! GL draw 0x502\`** (GL_INVALID_OPERATION) on world geometry draw calls (vao=4) and UI/ImGui (vao=15,16).
- **109× \`! shader compilation failed\`** across two main shaders:
  - \`accum_volumetric_sun_nomsaa.ps\` — undeclared identifiers (RAY_SAMPLES, density, deltaDepth, delta, coeff, direction).
  - \`accum_spot_fullsize_nomsaa.ps\` — preprocessor directive errors at lines 4486 / 5064 / 5178 (post-include line numbers).
  - \`accum_volumetric.ps\` — similar.
- **50× \`OpenGL: 0x500\` Invalid compressed 3D subtexture** (\`water_sbumpvolume.dds\`) — known Apple GL limitation, separate from this issue.

## Root cause — accum_volumetric_sun.ps (clear, fixable)

This is the SAME regression-class we created when fixing the SSAO cascade. Engine \`rgl_shaders.cpp:348-403\` makes \`SUN_SHAFTS_QUALITY\` always-defined to satisfy Apple GL preprocessor (which rejects \`#if X\` when X is undefined). User has \`r2_sun_shafts st_opt_off\` → \`SUN_SHAFTS_QUALITY=0\`.

Shader \`accum_volumetric_sun.ps:12\` then does:
\`\`\`glsl
#ifdef SUN_SHAFTS_QUALITY  // TRUE (define exists, even though 0)
    #if SUN_SHAFTS_QUALITY==1
        #define RAY_SAMPLES 20
    #elif SUN_SHAFTS_QUALITY==2
        #define RAY_SAMPLES 20
    #elif SUN_SHAFTS_QUALITY==3
        #define RAY_SAMPLES 40
    #endif
#endif
\`\`\`

No branch matches → \`RAY_SAMPLES\` never defined → code below using it produces "undeclared identifier".

Line 56 has the inverse pattern: \`#ifndef SUN_SHAFTS_QUALITY\` (returns black) — now always FALSE → falls to \`#else\` path which requires RAY_SAMPLES.

Fix: replace \`#ifdef SUN_SHAFTS_QUALITY\` → \`#if SUN_SHAFTS_QUALITY > 0\` and \`#ifndef SUN_SHAFTS_QUALITY\` → \`#if SUN_SHAFTS_QUALITY == 0\` in this shader.

## Hypothesis — 0x502 cascade

When \`accum_volumetric_sun_nomsaa.ps\` fails to compile, the engine likely tries to render the volumetric-sun pass with no/broken program bound → GL_INVALID_OPERATION on the draw → 0x502 spam. Fixing the shader should kill the 0x502 cascade.

## Root cause — accum_spot_fullsize_nomsaa.ps (deeper)

Different error class: "incorrect preprocessor directive". At preprocessed lines 4486 / 5064 / 5178. Likely another \`#if defined(X) && Y\` pattern where \`Y\` is undefined → Apple GL strict parser fails. Needs separate investigation — included as second item in this issue.

## Plan

1. Fix \`accum_volumetric_sun.ps\` (this session, immediate).
2. Re-verify: ship build, user plays Yanov + bunker, check log for residual shader fails + 0x502 count.
3. If \`accum_spot_fullsize_nomsaa\` still fails: separate sub-fix to find the offending preprocessor pattern.
4. If 0x502 count drops to ~0: CHK_GL clean run passes, tick done-criteria.
5. If 0x502 persists despite shader fix: investigate independently (vao binding ordering, ImGui interleave).

## Branch

\`issue-22-shader-compile-cascades\`.

**Comment by blackden** [comment]
First commit landed: 46743dba5 — fix \`accum_volumetric_sun.ps\` for SUN_SHAFTS_QUALITY=0 path. Lines 12 (#ifdef → #if > 0) and 56 (#ifndef → #if == 0).

Build is shipping. Will request user re-runs the same scenes (Yanov + bunker + outdoor) to verify:

1. \`! shader compilation failed: gl\\\\accum_volumetric_sun*\` no longer appears in log.
2. \`! GL draw 0x502\` cascade reduced or eliminated.
3. No new shader fails surface from the fix.

If 0x502 drops to ~0 → CHK_GL clean run passes, Block 2 done. If \`accum_spot_fullsize_nomsaa.ps\` still in log, follow-up commit on same branch for that preprocessor pattern.
